version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ./migrations:/migrations
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/warehouse?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    command: 
      - "-path=/migrations"
      - "-database=$$DB_URL"
      - "up"
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/warehouse?sslmode=disable"
      HTTP_PORT: "8080"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  postgres_data: