services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ../migrations:/migrations
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/warehouse?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    command: 
      - "-path=/migrations"
      - "-database=postgres://postgres:postgres@postgres:5432/warehouse?sslmode=disable"
      - "up"

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/warehouse?sslmode=disable"