http:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

postgres:
  host: "postgres"
  port: "5432"
  username: "postgres"
  password: "postgres"
  db_name: "warehouse"
  ssl_mode: "disable"